cd pokemon
cd front
magick bulbasaur.png ivysaur.png venusaur.png charmander.png charmeleon.png charizard.png squirtle.png wartortle.png totartle.png pikachu.png raichu.png raichua.png gorochu.png eevee.png vaporeon.png jolteon.png flareon.png espeon.png +append ../row1.png
magick umbreon.png leafeon.png glaceon.png sylveon.png rattata.png raticate.png raticatea.png pidgey.png pidgeotto.png pidgeot.png konya.png meowth.png persian.png persiana.png perrserker.png caterpie.png metapod.png butterfree.png +append ../row2.png
magick weedle.png beedrill.png kokana.png kasanagi.png carapthor.png spearow.png fearow.png ekans.png arbok.png sandshrew.png sandslash.png sandslasha.png nidoranf.png nidorina.png nidoqueen.png nidoranm.png nidorino.png nidoking.png nidoreign.png +append ../row3.png
magick bittybat.png zubat.png golbat.png crobat.png geodude.png graveler.png golem.png golema.png paras.png parasect.png clefairy.png clefable.png jigglypuff.png wigglytuff.png mikon.png vulpix.png ninetales.png ninetalesa.png +append ../row4.png
magick growlithe.png arcanine.png arcanineh.png mankey.png primeape.png annihilape.png oddish.png gloom.png vileplume.png bellossom.png bellsprout.png weepinbell.png victreebel.png tsubomitto.png magikarp.png gyarados.png gyopin.png goldeen.png +append ../row5.png
magick seaking.png venonat.png venomoth.png cheep.png jabetta.png psyduck.png weirduck.png golduck.png poliwag.png poliwhirl.png poliwrath.png politoed.png abra.png kadabra.png alakazam.png lickitung.png lickilicky.png +append ../row6.png
magick drowzee.png hypno.png diglett.png dugtrio.png dugtrioa.png wiglett.png wugtrio.png onix.png steelix.png kotora.png gaotora.png gorotora.png voltorb.png electrode.png electrodeh.png tentacool.png tentacruel.png  +append ../row7.png
magick toedscool.png toedscruel.png blottle.png pendraken.png ribbito.png croakozuna.png magnemite.png magnetite.png magneton.png magnezone.png machop.png machoke.png machamp.png crocky.png krabby.png kingler.png slowpoke.png +append ../row8.png
magick slowbro.png slowbrog.png slowking.png slowkingg.png puchikoon.png ponyta.png rapidash.png rapidashg.png deer.png monja.png tangela.png tangrowth.png barunda.png gastly.png haunter.png gengar.png cubone.png +append ../row9.png
magick marowak.png marowaka.png guardia.png farfetchd.png madaamu.png sirfetchd.png doduo.png dodrio.png grimer.png muk.png muka.png koffing.png weezing.png weezingg.png ditto.png animon.png mr.mime.png +append ../row10.png
magick mr.rime.png cactus.png hitmonchan.png hitmonlee.png hitmontop.png shellder.png cloyster.png taaban.png staryu.png starmie.png seel.png dewgong.png blastyke.png blastoise.png horsea.png seadra.png kingdra.png +append ../row11.png
magick jagg.png exeggcute.png exeggutor.png exeggutora.png rhyhorn.png rhydon.png rhyperior.png scyther.png scizor.png kleavor.png pinsir.png purakkusu.png kangaskhan.png trampel.png tauros.png taurospcombat.png taurospaqua.png +append ../row12.png
magick taurospblaze.png chansey.png blissey.png skimper.png bawligua.png cryithan.png jynx.png buu.png electabuzz.png electivire.png magmar.png magmortar.png lapras.png porygon.png porygon2.png porygonz.png omanyte.png +append ../row13.png
magick omastar.png kabuto.png kabutops.png aerodactyl.png decilla.png gyaoon.png omega.png snorlax.png screamtail.png sandyshocks.png dratini.png dragonair.png dragonite.png articuno.png articunog.png zapdos.png zapdosg.png +append ../row14.png
magick moltres.png moltresg.png mewtwo.png mew.png meltan.png melmetal.png +append ../row15.png
cd ..
magick row1.png row2.png row3.png row4.png row5.png row6.png row7.png row8.png row9.png row10.png row11.png row12.png row13.png row14.png row15.png -append gallery/front_sprites.png
del row1.png row2.png row3.png row4.png row5.png row6.png row7.png row8.png row9.png row10.png row11.png row12.png row13.png row14.png row15.png

cd back
magick bulbasaurb.png ivysaurb.png venusaurb.png charmanderb.png charmeleonb.png charizardb.png squirtleb.png wartortleb.png totartleb.png pikachub.png raichub.png raichuab.png gorochub.png eeveeb.png vaporeonb.png jolteonb.png flareonb.png espeonb.png +append ../row1.png
magick umbreonb.png leafeonb.png glaceonb.png sylveonb.png rattatab.png raticateb.png raticateab.png pidgeyb.png pidgeottob.png pidgeotb.png konyab.png meowthb.png persianb.png persianab.png perrserkerb.png caterpieb.png metapodb.png butterfreeb.png +append ../row2.png
magick weedleb.png beedrillb.png kokanab.png kasanagib.png carapthorb.png spearowb.png fearowb.png ekansb.png arbokb.png sandshrewb.png sandslashb.png sandslashab.png nidoranfb.png nidorinab.png nidoqueenb.png nidoranmb.png nidorinob.png nidokingb.png nidoreignb.png +append ../row3.png
magick bittybatb.png zubatb.png golbatb.png crobatb.png geodudeb.png gravelerb.png golemb.png golemab.png parasb.png parasectb.png clefairyb.png clefableb.png jigglypuffb.png wigglytuffb.png mikonb.png vulpixb.png ninetalesb.png ninetalesab.png +append ../row4.png
magick growlitheb.png arcanineb.png arcaninehb.png mankeyb.png primeapeb.png annihilapeb.png oddishb.png gloomb.png vileplumeb.png bellossomb.png bellsproutb.png weepinbellb.png victreebelb.png tsubomittob.png magikarpb.png gyaradosb.png gyopinb.png goldeenb.png +append ../row5.png
magick seakingb.png venonatb.png venomothb.png cheepb.png jabettab.png psyduckb.png weirduckb.png golduckb.png poliwagb.png poliwhirlb.png poliwrathb.png politoedb.png abrab.png kadabrab.png alakazamb.png lickitungb.png lickilickyb.png +append ../row6.png
magick drowzeeb.png hypnob.png diglettb.png dugtriob.png dugtrioab.png wiglettb.png wugtriob.png onixb.png steelixb.png kotorab.png gaotorab.png gorotorab.png voltorbb.png electrodeb.png electrodehb.png tentacoolb.png tentacruelb.png  +append ../row7.png
magick toedscoolb.png toedscruelb.png blottleb.png pendrakenb.png ribbitob.png croakozunab.png magnemiteb.png magnetiteb.png magnetonb.png magnezoneb.png machopb.png machokeb.png machampb.png crockyb.png krabbyb.png kinglerb.png slowpokeb.png +append ../row8.png
magick slowbrob.png slowbrogb.png slowkingb.png slowkinggb.png puchikoonb.png ponytab.png rapidashb.png rapidashgb.png deerb.png monjab.png tangelab.png tangrowthb.png barundab.png gastlyb.png haunterb.png gengarb.png cuboneb.png +append ../row9.png
magick marowakb.png marowakab.png guardiab.png farfetchdb.png madaamub.png sirfetchdb.png doduob.png dodriob.png grimerb.png mukb.png mukab.png koffingb.png weezingb.png weezinggb.png dittob.png animonb.png mr.mimeb.png +append ../row10.png
magick mr.rimeb.png cactusb.png hitmonchanb.png hitmonleeb.png hitmontopb.png shellderb.png cloysterb.png taabanb.png staryub.png starmieb.png seelb.png dewgongb.png blastykeb.png blastoiseb.png horseab.png seadrab.png kingdrab.png +append ../row11.png
magick jaggb.png exeggcuteb.png exeggutorb.png exeggutorab.png rhyhornb.png rhydonb.png rhyperiorb.png scytherb.png scizorb.png kleavorb.png pinsirb.png purakkusub.png kangaskhanb.png trampelb.png taurosb.png taurospcombatb.png taurospaquab.png +append ../row12.png
magick taurospblazeb.png chanseyb.png blisseyb.png skimperb.png bawliguab.png cryithanb.png jynxb.png buub.png electabuzzb.png electivireb.png magmarb.png magmortarb.png laprasb.png porygonb.png porygon2b.png porygonzb.png omanyteb.png +append ../row13.png
magick omastarb.png kabutob.png kabutopsb.png aerodactylb.png decillab.png gyaoonb.png omegab.png snorlaxb.png screamtailb.png sandyshocksb.png dratinib.png dragonairb.png dragoniteb.png articunob.png articunogb.png zapdosb.png zapdosgb.png +append ../row14.png
magick moltresb.png moltresgb.png mewtwob.png mewb.png meltanb.png melmetalb.png +append ../row15.png
cd ..
magick row1.png row2.png row3.png row4.png row5.png row6.png row7.png row8.png row9.png row10.png row11.png row12.png row13.png row14.png row15.png -append gallery/back_sprites.png
del row1.png row2.png row3.png row4.png row5.png row6.png row7.png row8.png row9.png row10.png row11.png row12.png row13.png row14.png row15.png
